[package]
name = "req-rs"
version = "0.1.0"
authors = ["stsysd <000stsysd000@gmail.com>"]
edition = "2018"

[[bin]]
name = "req"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.10.7", features=["json", "blocking"] }
toml = "0.5.8"
serde_json = "1.0.61"
serde = "1.0.118"
serde_derive = "1.0.118"
structopt = "0.3.21"
regex = "1.4.5"
once_cell = "1.7.2"
dotenv = "0.15.0"
