[tasks.get]
GET = 'https://httpbin.org/get'

[tasks.post]
POST = 'https://httpbin.org/post'

[tasks.post.headers]
Authorization = 'Token ${SECRET_TOKEN}'
Content-Type = 'application/json'

[tasks.post.body.json]
name = '$NAME'

[variables]
GREETING_MESSAGE = 'hello $NAME'
SECRET_TOKEN = 'default_token'
NAME = 'hoge'
