[req.default]
GET = 'https://httpbin.org/get'

[req.default.queries]
foo = ["$NAME", "bar"]


[req.post]
POST = 'https://httpbin.org/post'

[req.post.headers]
Authorization= 'Token $TOKEN'
Content-Type = 'application/json'

[req.post.body.json]
name = '$NAME'

[values]
GREETING_MESSAGE = 'hello $NAME'
NAME = 'hoge'
TOKEN = 'foobar'